--[[
***** How to Setup a vehicle_names.lua for Custom Addon Vehicles *****
* Create a vehicle_names.lua & past the below Code
function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	--Example 1: AddTextEntry('SPAWN_NAME_HERE', 'VEHICLE_NAME_HERE')
	--Example 2: AddTextEntry('f350', '2013 Ford F350')
end)
]]


function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry('BRABUS500', 'Brabus 500')
	AddTextEntry('EVO10', 'Evo 10')
	AddTextEntry('SUPERKART', 'Go Kart')
	AddTextEntry('FERRARI812', '812')
	AddTextEntry('C6Z06', 'Corvette')
	AddTextEntry('BEETLE2003', 'Beetle')
	AddTextEntry('BELAIR57', '57 Belair')
	AddTextEntry('M4F82', 'F82 M4')
	AddTextEntry('contss18c', 'Bentley Continental')
	AddTextEntry('yz250f', 'YZ 250F')
	AddTextEntry('MUSTANG', 'Ford Mustang')
	AddTextEntry('LP700', 'LP 700')
	AddTextEntry('CENTENARIO', 'LP 770')
	AddTextEntry('cbrr', 'Honda CBRR')
	AddTextEntry('EK9', 'Honda EK9 Civic')
	AddTextEntry('FGT', '2005 GT')
	AddTextEntry('6str', 'Gauntlet 6STR')
    AddTextEntry('evo8', 'Evo 8')
	AddTextEntry('FOCUSRS', 'Ford Focus')
	AddTextEntry('e36rb', 'BMW E36')
	AddTextEntry('GTR', 'Nissan GTR')
	AddTextEntry('G65', 'Mercedes G65')
	AddTextEntry('s200', 'Honda S2000')
	AddTextEntry('ast', 'AM Vanquish')
	AddTextEntry('amggtr', 'AMG GTR')
	AddTextEntry('gto06', 'Pontiac GTO')
	AddTextEntry('foxbody', 'Mustang Foxbody')
	AddTextEntry('na6', 'Mazda Miata')
	AddTextEntry('SkylineGTR', 'Nissan Skyline')
	AddTextEntry('URUS', 'Lamborghini Urus')
	AddTextEntry('FENYR', 'Lykan Fenyr')
	AddTextEntry('C63S', 'Mercedes C63S')
	AddTextEntry('16CHARGER', 'Dodge Charger')
	AddTextEntry('GT86', 'Toyota GT86')
	AddTextEntry('MODELS', 'Model S')
	AddTextEntry('SUPRA2', 'Toyota Supra')
	AddTextEntry('69CHARGER', '1969 Charger')
	AddTextEntry('CHALLENGER', '16 Challenger')
	AddTextEntry('Escalade', 'Cadillac Escalade')
	AddTextEntry('911TURBOS', '911 TurboS')
	AddTextEntry('Ageraone', 'Agera One')
	AddTextEntry('918SPYDER', '918 Spyder')
	AddTextEntry('SSTI', 'Subaru WRX')
	AddTextEntry('WRAITH', 'RR Wraith')
	AddTextEntry('SLS', 'SLS')
	AddTextEntry('DIVO', 'Bugatti Divo')
	AddTextEntry('vantage', 'AM Vantage')
	AddTextEntry('GHIS2', 'Ghibli')
	AddTextEntry('Supercab', 'Saleen Supercab')
	AddTextEntry('RS7', 'Audi RS7')
	AddTextEntry('RS6', 'Audi RS6')
	AddTextEntry('superleg', 'AM Superleggera')
	AddTextEntry('RRSTART', 'Rangerover')
	AddTextEntry('yzfr6', 'Yz fr6')
	AddTextEntry('M4SP', 'BMW M4')
	AddTextEntry('demon', 'Dodge Demon')
	AddTextEntry('RC350', 'Lexus RC350')
	AddTextEntry('alfieri', 'Maserati Alfieri')
	AddTextEntry('ss', 'Chevrolet SS')
	AddTextEntry('EVO9', 'Evo 9')
	AddTextEntry('franco125', 'Franco Yacht')
	AddTextEntry('Trackhawk', 'Jeep Trackhawk')
	AddTextEntry('eleanor', 'Ford Eleanor')
	AddTextEntry('Italia458', 'Italia 458')
	AddTextEntry('wheelchair', 'Wheelchair')
	AddTextEntry('W210', 'Mercedes W210')
	AddTextEntry('M5', 'BMW M5')
	AddTextEntry('M8', 'BMW M8')
	AddTextEntry('530xd', 'BMW 530 DONK')
	AddTextEntry('JESKO2020x', 'Jesko')
	AddTextEntry('gallardos', 'Gallardo S')
	AddTextEntry('yarishb', 'Toyota Yaris')
	AddTextEntry('MK7', 'Golf GTI')
	AddTextEntry('I8BMW', 'BMW i8')
	AddTextEntry('R8', 'Audi R8')
	AddTextEntry('FK8', 'Honda Civi Type-R')
	AddTextEntry('HVROD', 'Harley FatBoy')
	AddTextEntry('GMCYD', 'GMC Yukon')
	AddTextEntry('F100', '1970 F100')
	AddTextEntry('bmwe65', 'BMW E65')
	AddTextEntry('Caprice', 'Caprice')
	AddTextEntry('Caprice2', 'Caprice')
	AddTextEntry('16expm', 'Ford Explorer')
	AddTextEntry('19hoem', 'Chevrolet Tahoe')
	AddTextEntry('18charger', 'Charger')
	AddTextEntry('tau', 'Ford Taurus')
	AddTextEntry('cvpi', 'Ford CrownVictoria')
	AddTextEntry('camaro', 'Chevrolet Camaro')
	AddTextEntry('16exp', 'Explorer')
	AddTextEntry('19hoe', 'Tahoe')
	AddTextEntry('polsch3', 'U Schafter')
	AddTextEntry('policefelon', 'U Felon')
	AddTextEntry('hevo', 'Huracan')
	AddTextEntry('1200RT', 'BMW 1200RT')
	AddTextEntry('FD', 'Mazda RX7')
	AddTextEntry('teslax', 'Tesla X')
	AddTextEntry('2014rs5', 'Spooky Audi RS5')
	AddTextEntry('acuransx', 'Acura NSX')
	AddTextEntry('Sal', 'Saleen Mustang')
	AddTextEntry('silvia', 'Silvia S15')
	AddTextEntry('lexsc300', 'Lexus SC300')
	AddTextEntry('r32', 'Nissan R32')
	AddTextEntry('floridasky', 'Buick Skylark')
	AddTextEntry('X6M', 'MOB X6M')
	AddTextEntry('H6', 'Hummer')
	AddTextEntry('720s', 'McLaren 720s')
	AddTextEntry('650S', 'McLaren 650S')
	AddTextEntry('LP700', 'Lamborghini LP700')
	AddTextEntry('Tributo', 'Ferrari Tributo')
	AddTextEntry('BUGATTI', 'Bugatti Chiron')
	AddTextEntry('MASGT', 'Maserati GT')
	AddTextEntry('INTEGRA', 'Honda Integra')
	AddTextEntry('s1000', 'BMW S1000')
	AddTextEntry('DLOADER5', 'Duneloader 5')
	AddTextEntry('96imp', 'Impala SS DONK')
	AddTextEntry('gt17', 'Ford GT')
	AddTextEntry('MX5', 'Mazda MX5 Turkey')
	AddTextEntry('Transam', 'Pontiac Transam WS6')
	AddTextEntry('LWGTR', 'Libertywalk GTR')
	AddTextEntry('roadrun', 'Sandking XXL')
	AddTextEntry('PENTRO', 'Maibatsu Pentro')
	AddTextEntry('F550', 'F550')
	AddTextEntry('SILV', 'Chevy Silverado')
	AddTextEntry('hdwrecker', 'Kenworth W900')
	AddTextEntry('DiabloSV', 'Lamborghini Diablo')
	AddTextEntry('gsxr', 'Suzuki GSX-R')
	AddTextEntry('Viper', 'Dodge Viper')
	AddTextEntry('DYNAKING', 'Harley DynaKing')
	AddTextEntry('FF150', 'Ford F150')
	AddTextEntry('POLRAPTOR', 'Ford Raptor')
	AddTextEntry('fordho', 'Ford Hoonigan')
	AddTextEntry('TAMPAR', 'Tampa')
	AddTextEntry('SIXSIX6', 'Mercedes 6x6')
	AddTextEntry('Slaver', 'LostMC Slave')
	AddTextEntry('TRX', 'Winter RAM D1500')
	AddTextEntry('DONKY', 'Caprice 75')
	AddTextEntry('m4comp', 'GoodFellas M4')
	AddTextEntry('bugattiv', 'Bugatti Veyron')
	AddTextEntry('COQUETTE4', 'D10 Coquette')
	AddTextEntry('LWCC63', 'New Years LW C63')
	AddTextEntry('SRTT2018', 'Durango SRT')
	AddTextEntry('pmansory', 'Pasta Porsche')
	AddTextEntry('lc500', 'Lexus LC500')
	AddTextEntry('por718gt4', 'Porsche Cayman GT4')
	AddTextEntry('S600W220', 'Mercedes S600')
	AddTextEntry('WRXWBB', 'Subaru WRX WB')
	AddTextEntry('IndianCDH', 'Indian CDH')
	AddTextEntry('ZX10R', 'Ninja ZX10R')
	AddTextEntry('P1', 'Mclaren Senna')
	AddTextEntry('BC', 'Pagani Huayra')
	AddTextEntry('Rubicon3d', 'Jeep Rubicon')
	AddTextEntry('z48', 'BMW Z4')
	AddTextEntry('2019zr1', 'Corvette ZR1')
	AddTextEntry('fxxk', 'Ferrari FXXK')
	AddTextEntry('SIL80', 'Nissan SIL80')

end)