-- Manifest Version
resource_manifest_version '77731fab-63ca-442c-a67b-abc70f28dfa5'

-- Client Scripts
client_script 'client/main.lua'

-- Server Scripts
server_script 'server/main.lua'

-- NUI Default Page
ui_page('client/html/index.html')

-- Files needed for NUI
-- DON'T FORGET TO ADD THE SOUND FILES TO THIS!
files {
    'client/html/index.html',
    'client/html/sounds/demo.ogg',
    'client/html/sounds/beeper2.ogg',
    'client/html/sounds/BellStartEnd.ogg',
    'client/html/sounds/beltalarm.ogg',
    'client/html/sounds/betup.ogg',
    'client/html/sounds/buckle.ogg',
    'client/html/sounds/byenow.ogg',
    'client/html/sounds/cant_hide_boi.ogg',
    'client/html/sounds/cell.ogg',
    'client/html/sounds/cellcall.ogg',
    'client/html/sounds/chime.ogg',
    'client/html/sounds/clear_the_area.ogg',
    'client/html/sounds/Clothes1.ogg',
    'client/html/sounds/consume.ogg',
    'client/html/sounds/crash01.ogg',
    'client/html/sounds/Cuff.ogg',
    'client/html/sounds/deepfried.ogg',
    'client/html/sounds/dice.ogg',
    'client/html/sounds/dont_make_me.ogg',
    'client/html/sounds/doorbell.ogg',
    'client/html/sounds/DoorClose.ogg',
    'client/html/sounds/doorknock.ogg',
    'client/html/sounds/DoorOpen.ogg',
    'client/html/sounds/drop_a_missile.ogg',
    'client/html/sounds/ems.ogg',
    'client/html/sounds/flashbang.ogg',
    'client/html/sounds/freeze_lspd.ogg',
    'client/html/sounds/HighPrioCrime.ogg',
    'client/html/sounds/gdoor.ogg',
    'client/html/sounds/get_out_of_here_now.ogg',
    'client/html/sounds/give_yourself_up.ogg',
    'client/html/sounds/handcuff.ogg',
    'client/html/sounds/heartbeep.ogg',
    'client/html/sounds/heartbeep2.ogg',
    'client/html/sounds/howhelp.ogg',
    'client/html/sounds/impactdrill.ogg',
    'client/html/sounds/its_over_for_you.ogg',
    'client/html/sounds/jaildoor.ogg',
    'client/html/sounds/jumpland.ogg',
    'client/html/sounds/keydoors.ogg',
    'client/html/sounds/lock.ogg',
    'client/html/sounds/LockerOpen.ogg',
    'client/html/sounds/lockpick.ogg',
    'client/html/sounds/metaldetected.ogg',
    'client/html/sounds/metaldetector.ogg',
    'client/html/sounds/move_along_people.ogg',
    'client/html/sounds/mic_click_on.ogg',
    'client/html/sounds/mic_click_off.ogg',
    'client/html/sounds/off.ogg',
    'client/html/sounds/on.ogg',
    'client/html/sounds/ooff.ogg',
    'client/html/sounds/oon.ogg',
    'client/html/sounds/Pager.ogg',
    'client/html/sounds/payphoneend.ogg',
    'client/html/sounds/payphoneringing.ogg',
    'client/html/sounds/payphonestart.ogg',
    'client/html/sounds/photo.ogg',
    'client/html/sounds/pinpull.ogg',
    'client/html/sounds/PlayCard.ogg',
    'client/html/sounds/purge.ogg',
    'client/html/sounds/radioclick.ogg',
    'client/html/sounds/radiostatic1.ogg',
    'client/html/sounds/radiostatic2.ogg',
    'client/html/sounds/radiostatic3.ogg',
    'client/html/sounds/rapell.ogg',
    'client/html/sounds/robberydraw.ogg',
    'client/html/sounds/robberyglass.ogg',
    'client/html/sounds/robberyglassbreak.ogg',
    'client/html/sounds/ruletka.ogg',
    'client/html/sounds/RumbleStart.ogg',
    'client/html/sounds/s.ogg',
    'client/html/sounds/seatbelt.ogg',
    'client/html/sounds/seatbeltoff.ogg',
    'client/html/sounds/security-alarm.ogg',
    'client/html/sounds/shoot_to_kill.ogg',
    'client/html/sounds/Shop.ogg',
    'client/html/sounds/SodaMachine.ogg',
    'client/html/sounds/soff.ogg',
    'client/html/sounds/Stash.ogg',
    'client/html/sounds/StashOpen.ogg',
    'client/html/sounds/stop_dont_move.ogg',
    'client/html/sounds/stop_or_executed.ogg',
    'client/html/sounds/stay_right_there.ogg',
    'client/html/sounds/stop_the_f_car.ogg',
    'client/html/sounds/stop_vehicle.ogg',
    'client/html/sounds/stop_vehicle-2.ogg',
    'client/html/sounds/stupid.ogg',
    'client/html/sounds/stupid1.ogg',
    'client/html/sounds/stupid2.ogg',
    'client/html/sounds/tada.ogg',
    'client/html/sounds/this_is_the_lspd.ogg',
    'client/html/sounds/towtruck.ogg',
    'client/html/sounds/towtruck2.ogg',
    'client/html/sounds/unbuckle.ogg',
    'client/html/sounds/Uncuff.ogg',
    'client/html/sounds/unlock.ogg',
    'client/html/sounds/ventilator.ogg',
    'client/html/sounds/warehousealert.ogg',
    'client/html/sounds/warehousealert2.ogg',
    'client/html/sounds/windows.ogg',
    'client/html/sounds/maleuse.ogg',
    'client/html/sounds/malegroan.ogg',
    'client/html/sounds/echobreathe.ogg',
    'client/html/sounds/femalegroan.ogg',
    'client/html/sounds/doorexit.ogg',
    'client/html/sounds/doorenter.ogg',
    'client/html/sounds/zip.ogg'



}


